---
title: ""
---

<iframe width="560" height="315" src="https://www.youtube.com/embed/wvqw6PPl0eY" frameborder="0" allowfullscreen></iframe>

## Welcome to the Protocol Hackathon

#### 19.+20. December, 2016
#### Heinrich-Heine University Düsseldorf, Institute of Synthetic Microbiology

---
### Idea

Ever spend hours on searching for the protocol that was used in a paper? It can be much simpler than that if researchers would openly share their protocols. The idea for this hackathon is exactly this. We want to show a way to __share your protocols online and get credit for your work__. We found that [protocols.io](https://www.protocols.io) is the perfect platform for this endeavor. But it is not only about sharing your procotols so others can easier access your work. You can also add changes to existing protocols, if you found that they weren't working the way they were suppose to, and help to improve them. Futhermore, it creates a platform to collect all the protocols you are using in the lab, including protocols from commercial suppliers such as [New England Biolabs](https://www.protocols.io/groups/new-england-biolabs-neb). No more searchring for a protocol on a lab computer or USB drive to show it to a new lab member. Just add her to the group and she will be able to access all protocols online through the web browser or a mobile app.

### How to get involved

You can either attend the hackathon at HHU in Düsseldorf. However, we have only limited space so please let me know if you consider showing up in person by simply writing me an [email](mailto:nicolasschmelling@gmail.com).

If you want to connect from outside, I have an [etherpad](https://public.etherpad-mozilla.org/p/dfttlIanxu) set up for you or you can use the issue tracker in the [GitHub repo](https://github.com/schmelling/protocol_hackathon). I try to post some tasks prior to the hackathon that you can work on in case you don't have any protocols to upload to protocols.io.

### Schedule
__Location: Heinrich-Heine University Düsseldorf, Room:tba__

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1627.124613872837!2d6.798101831702421!3d51.1879986809241!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sde!2sde!4v1481289357392" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

#### 19. December 2016
Time | Session
---- | -------
09:00 - 10:00 | [ORCID](https://orcid.org) Set up + Introduction to [protocols.io](https://www.protocols.io) (Mabye broadcasted on YouTube)
10:00 - 10:30 | How to upload a new protocol (Mabye broadcasted on YouTube)
10:30 - 12:00 | Hackathon Session I
12:00 - 13:00 | Lunch
13:00 - 18:00 | Hackathon Session II
18:00 - open end | Pizza & Beer *

<nowiki>*</nowiki> for motivated people: Hackathon Session II.2

#### 20. December 2016
Time | Session
---- | -------
10:00 - 12:00 | Hackathon Session III
12:00 - 13:00 | Lunch
13:00 - 15:00 | Hackathon Session IV
15:00 - open end | Logo Design + later Dinner & Beer

### Resources

* [ORCID](https://orcid.org)
* [protocols.io](https://www.protocols.io)
* [Protocol Template](https://docs.google.com/document/d/1NX-07dy9ptrPwhF9-g8ktGHTJ9HPI5JmEZK0bdv82fA/edit?usp=sharing)